export const LANGUAGES = [
  'auto',
  'English',
  'Russian',
  'Spanish', 
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Chinese',
  'Japanese',
  'Korean',
  'Arabic',
  'Hindi',
  'Turkish',
  'Dutch',
  'Polish',
  'Ukrainian',
  'Czech',
  'Slovak',
  'Bulgarian',
  'Croatian',
  'Serbian',
  'Slovenian',
  'Estonian',
  'Latvian',
  'Lithuanian',
  'Finnish',
  'Swedish',
  'Norwegian',
  'Danish',
  'Icelandic',
  'Greek',
  'Hebrew',
  'Thai',
  'Vietnamese',
  'Indonesian',
  'Malay',
  'Filipino',
  'Swahili',
  'Afrikaans',
  'Zulu',
  'Amharic',
  'Bengali',
  'Gujarati',
  'Kannada',
  'Malayalam',
  'Marathi',
  'Punjabi',
  'Tamil',
  'Telugu',
  'Urdu',
  'Nepali',
  'Sinhala',
  'Myanmar',
  'Khmer',
  'Lao',
  'Mongolian',
  'Kazakh',
  'Kyrgyz',
  'Tajik',
  'Turkmen',
  'Uzbek',
  'Georgian',
  'Armenian',
  'Azerbaijani',
  'Albanian',
  'Bosnian',
  'Macedonian',
  'Maltese',
  'Irish',
  'Welsh',
  'Scottish Gaelic',
  'Basque',
  'Catalan',
  'Galician',
  'Romanian',
  'Hungarian',
  'Persian',
  'Kurdish',
  'Pashto',
  'Dari',
  'Somali',
  'Hausa',
  'Yoruba',
  'Igbo'
];

export const STORAGE_KEYS = {
  API_KEY: 'ai-translator-api-key',
  SOURCE_LANG: 'ai-translator-source-lang',
  TARGET_LANG: 'ai-translator-target-lang',
  SOURCE_TEXT: 'ai-translator-source-text',
  TRANSLATED_TEXT: 'ai-translator-translated-text'
};
